import { useEffect, useState, ReactNode } from 'react'
import { Settings, SettingsContext } from './SettingsContextState'

const translations = {
  en: {
    dashboard: 'Dashboard',
    employees: 'Employees',
    settings: 'Settings',
    todaysCoverage: "Today's Coverage",
    coverageGaps: 'Coverage Gaps',
    noCoverage: 'No Coverage',
    covered: 'Covered',
    activeEmployees: 'Active Employees',
    totalEmployees: 'Total Employees',
    departments: 'Departments',
    shiftsToday: 'Shifts Today',
    noActiveEmployees: 'No active employees',
    addEmployee: 'Add Employee',
    editEmployee: 'Edit Employee',
    name: 'Name',
    role: 'Role',
    department: 'Department',
    status: 'Status',
    actions: 'Actions',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    confirmDelete: 'Are you sure you want to delete this?',
    employeeDetails: 'Employee Details',
    shifts: 'Shifts',
    addShift: 'Add Shift',
    editShift: 'Edit Shift',
    startTime: 'Start Time',
    endTime: 'End Time',
    companyName: 'Company Name',
    openingTime: 'Opening Time',
    closingTime: 'Closing Time',
    companyLogo: 'Company Logo',
    uploadLogo: 'Upload Logo',
    removeLogo: 'Remove Logo',
    language: 'Language',
    theme: 'Theme',
    dark: 'Dark',
    light: 'Light',
    businessSettings: 'Business Settings',
    generalSettings: 'General Settings',
    english: 'English',
    spanish: 'Spanish',
    day: 'Day',
    week: 'Week',
    date: 'Date',
    softwareUpdate: 'Software Update',
    currentVersion: 'Current Version',
    checkingForUpdates: 'Checking for updates...',
    upToDate: 'Up to date',
    available: 'available',
    download: 'Download',
    downloading: 'Downloading...',
    restartAndInstall: 'Restart & Install',
    updateError: 'Update Error',
    checkForUpdates: 'Check for updates',
    automaticUpdates: 'Automatic Updates',
    automaticUpdatesDesc: 'Download updates automatically when available',
    dashboardOverview: 'Overview of your employee directory inside this Electron app.',
    statusActive: 'Active',
    statusInactive: 'Inactive',
    statusOnLeave: 'On Leave',
    placeholderName: 'John Doe',
    placeholderRole: 'Software Engineer',
    placeholderDepartment: 'Engineering',
    hours: 'hours',
    deleteShiftConfirm: 'Delete shift?',
    shiftsDescription: 'Manage and schedule shifts for all employees.',
    searchEmployees: 'Search employees...',
    allDepartments: 'All Departments',
    employee: 'Employee',
    manageTeamMembers: 'Manage your team members.',
    defaultMonthlyHours: 'Default Monthly Hours',
    failedToSaveEmployee: 'Failed to save employee',
    failedToDeleteEmployee: 'Failed to delete employee',
    internalDashboard: 'Internal dashboard',
    session: 'Session',
    runtimeDetails: 'Electron runtime details below.',
    failedToSaveShift: 'Failed to save shift',
    loading: 'Loading...',
    month: 'Month',
    worked: 'Worked',
    agreed: 'Agreed',
    diff: 'Diff',
    noShiftsForDay: 'No shifts scheduled for this day',
    weekOf: 'Week of',
    coverageGapsRed: 'Coverage Gaps (Red)',
    shiftOutsideBusinessHoursConfirm: 'Shift is outside business hours. Do you want to proceed?',
    shiftOverlapError: 'This shift overlaps with another shift for the same employee.',
    filterBy: 'Filter by',
    allStatuses: 'All Statuses',
    allRoles: 'All Roles',
    clearFilters: 'Clear filters',
    edit: 'Edit',
    fileSizeTooLarge: 'File size too large. Please upload an image smaller than 2MB.',
    fileSizeLimit: 'Max 2MB. PNG, JPG, SVG.',
    appLogoAlt: 'App Logo',
    confirm: 'Confirm',
    error: 'Error',
    deleteEmployee: 'Delete Employee',
    deleteShift: 'Delete Shift',
    total: 'Total',
    owed: 'Owed',
    generatedOn: 'Generated on',
    exportSchedule: 'Export Schedule',
    schedule: 'Schedule',
    print: 'Print',
    printSchedule: 'Print Schedule',
    totalStaff: 'Hours without staff',
    preview: 'Preview',
    weeklySchedule: 'Weekly Schedule',
    defaultWeeklyHours: 'Default Weekly Hours',
    selectDepartment: 'Select Department',
    editWeeklyHours: 'Edit Weekly Hours',
    target: 'Target',
    targetWeekly: 'Weekly Target',
    targetMonthly: 'Monthly Target',
    summary: 'Summary',
    weekDiff: 'Weekly Diff',
    monthDiff: 'Monthly Diff',
    totalWorked: 'Total Worked',
    lifetimeBalance: 'Lifetime Balance',
    viewOptions: 'View Options',
    showCalendar: 'Show Calendar',
    visibleStats: 'Visible Stats',
    copyShifts: 'Copy Shifts',
    copyTargetHasDataWarning: 'Warning: The target period already has shifts',
    source: 'Source',
    shiftsToCopy: 'Shifts to Copy',
    targetDate: 'Target Date',
    selectAnyDayInTargetWeek: 'Select any day in the target week',
    selectAnyDayInTargetMonth: 'Select any day in the target month',
    copy: 'Copy',
    compactView: 'Compact View',
    days: 'Days',
    daysPerImage: 'Days per Image',
    auto: 'Auto',
    reports: 'Reports',
    reportsDescription: 'View historical records of closed months and employee balances.',
    closedMonths: 'Closed Months',
    noClosedMonths: 'No closed months found.',
    selectMonthToView: 'Select a month to view details',
    closed: 'Closed',
    closedOn: 'Closed on',
    workedHours: 'Worked Hours',
    paidAbsence: 'Paid Absence',
    unpaidAbsence: 'Unpaid Absence',
    payrollHours: 'Payroll Hours',
    exportCSV: 'Export CSV',
    exportCSVDescription: 'Export to CSV (Excel compatible)',
    absence: 'Absence',
    work: 'Work',
    fullDays: 'Full Days',
    isPaid: 'Is Paid?',
    bank_holiday: 'Bank Holiday',
    sick_leave: 'Sick Leave',
    unpaid: 'Unpaid',
    holiday: 'Holiday',
    other: 'Other',
    absenceType: 'Absence Type',
    consecutiveDaysNote: 'Creates consecutive absence entries (skips weekends if applicable)',
    clickToTargetEdit: 'Click to edit target',
    actualHours: 'Actual Hours',
    accumulatedBalance: 'Accumulated Balance',
    netBalance: 'Net Balance',
    targetHours: 'Target Hours',
    difference: 'Difference',
    monthClosedMessage: 'This month is closed. Unlock it to make changes.',
    payOffBalance: 'Pay Off Balance',
    balancePayOff: 'Balance Pay Off',
    balanceRemaining: 'Balance Remaining',
    balanceBefore: 'Balance Before',
    balanceAfter: 'Balance After',
    payOffHistory: 'History of manual balance adjustments and payoffs.',
    currentBalance: 'Current Balance',
    payOffExplanation: 'This action will create an adjustment to set the accumulated balance to zero.',
    description: 'Description',
    payOffPlaceholder: 'e.g. Paid out overtime',
    confirmPayOff: 'Pay Off',
    balanceHistory: 'Balance History',
    noAdjustments: 'No balance adjustments found',
    deleteAdjustmentConfirm: 'Are you sure you want to delete this adjustment?',
    amount: 'Amount',
    payOffAmount: 'Amount to Pay Off',
    locked: 'Locked',
    payOffSuccess: 'Balance adjustment applied to',
    payOffFailed: 'Failed to save balance adjustment',
    agreedHours: 'Agreed Hours',
    adjustmentAppliedTo: 'Adjustment will be applied to',
    warning: 'Warning',
    sourceEmployee: 'Source Employee',
    allEmployees: 'All Employees',
    copyTo: 'Copy To',
    sameEmployee: 'Same Employee(s)',
    specificEmployees: 'Specific Employee(s)',
    selectEmployees: 'Select Employees',
    deselectAll: 'Deselect All',
    selectAll: 'Select All',
    selectedDates: 'Selected Dates',
    updateAvailable: 'Update Available',
    versionAvailable: 'Version {version} is available.',
    downloadUpdate: 'Download Update',
    downloadingUpdate: 'Downloading Update...',
    updateReady: 'Update Ready',
    updateDownloaded: 'Version {version} has been downloaded.',
    restartInstall: 'Restart & Install',
    updateFailed: 'Update Failed',
    updateErrorGeneric: 'An error occurred while updating.',
    exportWeeklySchedule: 'Export Weekly Schedule',
    showSidebarCalendar: 'Show Sidebar Calendar',
    showSidebarCalendarDesc: 'Display a mini calendar in the navigation sidebar',
    showSideCalendar: 'Show Sidebar Calendar',
    showSideCalendarDesc: 'Display a mini calendar in the navigation sidebar',
    daysError: 'Number of days must be between 1 and 30',
    companyLogoAlt: 'Company Logo',
    unlockMonth: 'Unlock Month',
    unlockMonthWarningSubsequent: 'Warning: Subsequent months are closed. Unlocking this month may affect their balances.',
    unlockMonthConfirm: 'Are you sure you want to unlock this month?',
    cannotCloseMonth: 'Cannot Close Month',
    previousMonthNotClosed: 'Previous month must be closed first.',
    closeMonth: 'Close Month',
    closeMonthConfirm: 'Are you sure you want to close this month? This will lock the balances.',
    monthClosed: 'Month Closed',
    dataBackup: 'Data Backup',
    autoBackup: 'Automatic Backup',
    autoBackupDesc: 'Schedule automatic backups of your data',
    off: 'Off',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    recentBackups: 'Recent Backups',
    backupRetention: 'System keeps only the last 3 backups.',
    backupNow: 'Backup Now',
    noBackups: 'No backups available',
    restore: 'Restore',
    restoreBackup: 'Restore Backup',
    restoreWarning: 'WARNING: This will overwrite all current data with the backup data. This action cannot be undone. Are you sure you want to proceed?',
    liveRoster: 'Live Roster',
    scenarios: 'Draft Scenarios',
    createNewScenario: 'Create New Draft...',
    draftMode: 'Draft Mode',
    draftDescription: 'Changes here are saved automatically but do not affect the live roster.',
    publishScenario: 'Publish to Live',
    deleteScenario: 'Delete Draft',
    errorCreatingScenario: 'Failed to create scenario',
    confirmPublish: 'Are you sure you want to publish this scenario? This will overwrite the live roster for the covered period.',
    confirmDeleteScenario: 'Are you sure you want to delete this draft?',
    cloneFromLive: 'Clone from Live Roster',
    cloneDateRange: 'Clone Date Range',
    scenarioName: 'Scenario Name',
    scenarioDescription: 'Description',
    startDate: 'Start Date',
    endDate: 'End Date',
    cloneFromLiveHelp: 'Copies all shifts from the live roster within the selected date range to this draft scenario.',
    monthClosureDisabledInDraft: 'Month closure is disabled in Draft Mode',
    createScenario: 'Create Draft Scenario',
    clickToEditTarget: 'Click bar to edit target',
    calendar: 'Calendar',
    selectEmployee: 'Select Employee',
    numberOfDays: 'Number of Days',
    daysToHoursNote: 'Creates daily entries based on weekly average.',
    bankHoliday: 'Bank Holiday',
    sickLeave: 'Sick Leave',
    publishScenarioConfirm: 'Are you sure you want to publish this scenario? This will overwrite the live roster for the affected period.',
    deleteScenarioConfirm: 'Are you sure you want to delete this draft scenario? This action cannot be undone.',
    publish: 'Publish',
    create: 'Create',
    creating: 'Creating...',
    scenarioNamePlaceholder: 'e.g., Next Week Plan'
  },
  es: {
    dashboard: 'Panel de control',
    employees: 'Empleados',
    settings: 'Configuración',
    todaysCoverage: 'Cobertura de hoy',
    coverageGaps: 'Brechas de cobertura',
    noCoverage: 'Sin cobertura',
    covered: 'Cubierto',
    activeEmployees: 'Empleados activos',
    totalEmployees: 'Total de empleados',
    departments: 'Departamentos',
    shiftsToday: 'Turnos de hoy',
    noActiveEmployees: 'No hay empleados activos',
    addEmployee: 'Añadir empleado',
    editEmployee: 'Editar empleado',
    name: 'Nombre',
    role: 'Rol',
    department: 'Departamento',
    status: 'Estado',
    actions: 'Acciones',
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    confirmDelete: '¿Estás seguro de que quieres eliminar esto?',
    employeeDetails: 'Detalles del empleado',
    shifts: 'Turnos',
    addShift: 'Añadir turno',
    editShift: 'Editar turno',
    startTime: 'Hora de inicio',
    endTime: 'Hora de fin',
    companyName: 'Nombre de la empresa',
    openingTime: 'Hora de apertura',
    closingTime: 'Hora de cierre',
    companyLogo: 'Logotipo de la empresa',
    uploadLogo: 'Subir logo',
    removeLogo: 'Eliminar logo',
    language: 'Idioma',
    theme: 'Tema',
    dark: 'Oscuro',
    light: 'Claro',
    businessSettings: 'Configuración del negocio',
    generalSettings: 'Configuración general',
    english: 'Inglés',
    spanish: 'Español',
    day: 'Día',
    week: 'Semana',
    date: 'Fecha',
    manageTeamMembers: 'Gestiona los miembros de tu equipo.',
    defaultMonthlyHours: 'Horas mensuales predeterminadas',
    failedToSaveEmployee: 'Error al guardar empleado',
    failedToDeleteEmployee: 'Error al eliminar empleado',
    placeholderName: 'Juan Pérez',
    placeholderRole: 'Ingeniero de software',
    placeholderDepartment: 'Ingeniería',
    internalDashboard: 'Panel interno',
    session: 'Sesión',
    runtimeDetails: 'Detalles del tiempo de ejecución de Electron a continuación.',
    dashboardOverview: 'Resumen de su directorio de empleados dentro de esta aplicación Electron.',
    hours: 'horas',
    deleteShiftConfirm: '¿Eliminar turno?',
    failedToSaveShift: 'Error al guardar turno',
    loading: 'Cargando...',
    month: 'Mes',
    worked: 'Trabajado',
    agreed: 'Acordado',
    diff: 'Diferencia',
    noShiftsForDay: 'No hay turnos programados para este día',
    weekOf: 'Semana del',
    coverageGapsRed: 'Brechas de cobertura (rojo)',
    shiftsDescription: 'Gestione y programe turnos para todos los empleados.',
    searchEmployees: 'Buscar empleados...',
    allDepartments: 'Todos los departamentos',
    employee: 'Empleado',
    shiftOutsideBusinessHoursConfirm: 'El turno está fuera del horario comercial. ¿Quieres continuar?',
    shiftOverlapError: 'Este turno se superpone con otro turno para el mismo empleado.',
    filterBy: 'Filtrar por',
    allStatuses: 'Todos los estados',
    allRoles: 'Todos los roles',
    clearFilters: 'Borrar filtros',
    edit: 'Editar',
    fileSizeTooLarge: 'El archivo es demasiado grande. Por favor, sube una imagen de menos de 2MB.',
    fileSizeLimit: 'Máx 2MB. PNG, JPG, SVG.',
    appLogoAlt: 'Logotipo de la aplicación',
    confirm: 'Confirmar',
    error: 'Error',
    deleteEmployee: 'Eliminar empleado',
    deleteShift: 'Eliminar turno',
    total: 'Total',
    owed: 'Debido',
    generatedOn: 'Generado el',
    exportSchedule: 'Exportar horario',
    schedule: 'Horario',
    totalStaff: 'Horas sin personal',
    print: 'Imprimir',
    printSchedule: 'Imprimir horario',
    preview: 'Vista previa',
    weeklySchedule: 'Horario semanal',
    defaultWeeklyHours: 'Horas semanales predeterminadas',
    createNewDepartment: 'Crear nuevo departamento',
    selectDepartment: 'Seleccionar departamento',
    editWeeklyHours: 'Editar horas semanales',
    target: 'Objetivo',
    targetWeekly: 'Objetivo semanal',
    targetMonthly: 'Objetivo mensual',
    summary: 'Resumen',
    weekDiff: 'Dif. semanal',
    monthDiff: 'Dif. mensual',
    totalWorked: 'Total trabajado',
    lifetimeBalance: 'Balance total',
    viewOptions: 'Opciones de vista',
    showCalendar: 'Mostrar calendario',
    visibleStats: 'Estadísticas visibles',
    copyShifts: 'Copiar turnos',
    copyTargetHasDataWarning: 'Advertencia: El período de destino ya tiene turnos',
    source: 'Origen',
    shiftsToCopy: 'Turnos a copiar',
    targetDate: 'Fecha de destino',
    selectAnyDayInTargetWeek: 'Seleccione cualquier día en la semana de destino',
    softwareUpdate: 'Actualización de software',
    currentVersion: 'Versión actual',
    checkingForUpdates: 'Buscando actualizaciones...',
    upToDate: 'Actualizado',
    available: 'disponible',
    download: 'Descargar',
    downloading: 'Descargando...',
    restartAndInstall: 'Reiniciar e instalar',
    updateError: 'Error al actualizar',
    checkForUpdates: 'Buscar actualizaciones',
    automaticUpdates: 'Actualizaciones automáticas',
    automaticUpdatesDesc: 'Descargar actualizaciones automáticamente cuando estén disponibles',
    selectAnyDayInTargetMonth: 'Seleccione cualquier día en el mes de destino',
    copy: 'Copiar',
    compactView: 'Vista compacta',
    days: 'Días',
    daysPerImage: 'Días por imagen',
    auto: 'Auto',
    noClosedMonths: 'No se encontraron meses cerrados.',
    monthClosedMessage: 'Este mes está cerrado. Desbloquéalo para realizar cambios.',
    selectMonthToView: 'Selecciona un mes para ver los detalles',
    reports: 'Informes',
    reportsDescription: 'Ver registros históricos de meses cerrados y saldos de empleados.',
    closedMonths: 'Meses cerrados',
    liveRoster: 'Horario en vivo',
    scenarios: 'Escenarios borradores',
    createNewScenario: 'Crear nuevo borrador...',
    draftMode: 'Modo Borrador',
    draftDescription: 'Los cambios aquí se guardan automáticamente pero no afectan el horario en vivo.',
    publishScenario: 'Publicar en vivo',
    deleteScenario: 'Eliminar borrador',
    errorCreatingScenario: 'Error al crear el escenario',
    confirmPublish: '¿Estás seguro de que deseas publicar este escenario? Esto sobrescribirá el horario en vivo para el período cubierto.',
    confirmDeleteScenario: '¿Estás seguro de que deseas eliminar este borrador?',
    cloneFromLive: 'Clonar del horario en vivo',
    cloneDateRange: 'Rango de fechas para clonar',
    scenarioName: 'Nombre del escenario',
    scenarioDescription: 'Descripción',
    startDate: 'Fecha de inicio',
    endDate: 'Fecha de fin',
    cloneFromLiveHelp: 'Copia todos los turnos del horario en vivo dentro del rango de fechas seleccionado a este escenario borrador.',
    monthClosureDisabledInDraft: 'El cierre de mes está deshabilitado en modo borrador',
    closed: 'Cerrado',
    closedOn: 'Cerrado el',
    workedHours: 'Horas trabajadas',
    paidAbsence: 'Ausencia remunerada',
    unpaidAbsence: 'Ausencia no remunerada',
    payrollHours: 'Horas de nómina',
    exportCSV: 'Exportar CSV',
    exportCSVDescription: 'Exportar a CSV (compatible con Excel)',
    targetHours: 'Horas objetivo',
    actualHours: 'Horas reales',
    difference: 'Diferencia',
    accumulatedBalance: 'Saldo acumulado',
    netBalance: 'Balance neto',
    payOffBalance: 'Liquidar saldo',
    balancePayOff: 'Liquidación de saldo',
    balanceRemaining: 'Saldo restante',
    balanceBefore: 'Saldo anterior',
    balanceAfter: 'Saldo posterior',
    payOffHistory: 'Historial de ajustes manuales de saldo y liquidaciones.',
    currentBalance: 'Saldo actual',
    payOffExplanation: 'Esta acción creará un ajuste para poner el saldo acumulado a cero.',
    description: 'Descripción',
    payOffPlaceholder: 'ej. Horas extras pagadas',
    confirmPayOff: 'Liquidar',
    balanceHistory: 'Historial de saldos',
    noAdjustments: 'No se encontraron ajustes de saldo',
    deleteAdjustmentConfirm: '¿Estás seguro de que quieres eliminar este ajuste?',
    amount: 'Cantidad',
    payOffAmount: 'Cantidad a liquidar',
    absence: 'Ausencia',
    work: 'Trabajo',
    fullDays: 'Días completos',
    isPaid: '¿Está pagado?',
    bank_holiday: 'Festivo',
    sick_leave: 'Baja médica',
    unpaid: 'No remunerado',
    holiday: 'Vacaciones',
    other: 'Otro',
    absenceType: 'Tipo de ausencia',
    consecutiveDaysNote: 'Crea entradas de ausencia consecutivas (omite fines de semana si corresponde)',
    consecutivesDayNote: 'Crea entradas de ausencia consecutivas (omite fines de semana si corresponde)',
    clickToTargetEdit: 'Haz clic para editar el objetivo',
    showSidebarCalendar: 'Mostrar calendario lateral',
    showSidebarCalendarDesc: 'Mostrar un calendario pequeño en la barra lateral',
    showSideCalendar: 'Mostrar calendario lateral',
    showSideCalendarDesc: 'Mostrar un calendario pequeño en la barra lateral',
    statusActive: 'Activo',
    statusInactive: 'Inactivo',
    statusOnLeave: 'De baja',
    daysError: 'El número de días debe estar entre 1 y 30',
    locked: 'Bloqueado',
    payOffSuccess: 'Ajuste de saldo aplicado a',
    payOffFailed: 'Error al guardar el ajuste de saldo',
    agreedHours: 'Horas acordadas',
    adjustmentAppliedTo: 'El ajuste se aplicará a',
    updateAvailable: 'Actualización disponible',
    versionAvailable: 'La versión {version} está disponible.',
    downloadUpdate: 'Descargar actualización',
    downloadingUpdate: 'Descargando actualización...',
    updateReady: 'Actualización lista',
    updateDownloaded: 'La versión {version} se ha descargado.',
    restartInstall: 'Reiniciar e instalar',
    updateFailed: 'Actualización fallida',
    updateErrorGeneric: 'Ocurrió un error al actualizar.',
    warning: 'Advertencia',
    sourceEmployee: 'Empleado origen',
    allEmployees: 'Todos los empleados',
    copyTo: 'Copiar a',
    sameEmployee: 'Mismo(s) empleado(s)',
    specificEmployees: 'Empleado(s) específico(s)',
    selectEmployees: 'Seleccionar empleados',
    deselectAll: 'Deseleccionar todos',
    selectAll: 'Seleccionar todos',
    selectedDates: 'Fechas seleccionadas',
    exportPNG: 'Exportar PNG',
    exportPDF: 'Exportar PDF',
    page: 'Página',
    exportFailedConsole: 'Error al exportar. Por favor revise la consola para más detalles.',
    exportWeeklySchedule: 'Exportar horario semanal',
    unlockMonth: 'Desbloquear mes',
    unlockMonthWarningSubsequent: 'Advertencia: Los meses siguientes están cerrados. Desbloquear este mes puede afectar sus saldos.',
    unlockMonthConfirm: '¿Seguro que quieres desbloquear este mes?',
    cannotCloseMonth: 'No se puede cerrar el mes',
    previousMonthNotClosed: 'El mes anterior debe cerrarse primero.',
    closeMonth: 'Cerrar mes',
    closeMonthConfirm: '¿Seguro que quieres cerrar este mes? Esto bloqueará los saldos.',
    monthClosed: 'Mes cerrado',
    dataBackup: 'Copia de seguridad',
    autoBackup: 'Copia de seguridad automática',
    autoBackupDesc: 'Programar copias de seguridad automáticas de tus datos',
    off: 'Apagado',
    daily: 'Diariamente',
    weekly: 'Semanalmente',
    monthly: 'Mensualmente',
    recentBackups: 'Copias recientes',
    backupRetention: 'El sistema solo guarda las últimas 3 copias de seguridad.',
    backupNow: 'Crear copia ahora',
    noBackups: 'No hay copias de seguridad disponibles',
    restore: 'Restaurar',
    restoreBackup: 'Restaurar copia de seguridad',
    restoreWarning: 'ADVERTENCIA: Esto sobrescribirá todos los datos actuales con los datos de la copia de seguridad. Esta acción no se puede deshacer. ¿Estás seguro de que quieres continuar?',
    createScenario: 'Crear Escenario Borrador',
    clickToEditTarget: 'Haz clic en la barra para editar el objetivo',
    calendar: 'Calendario',
    selectEmployee: 'Seleccionar Empleado',
    numberOfDays: 'Número de Días',
    daysToHoursNote: 'Crea entradas diarias basadas en el promedio semanal.',
    bankHoliday: 'Festivo',
    sickLeave: 'Baja Médica',
    publishScenarioConfirm: '¿Estás seguro de que quieres publicar este escenario? Esto sobrescribirá el horario principal para el período afectado.',
    deleteScenarioConfirm: '¿Estás seguro de que quieres eliminar este borrador? Esta acción no se puede deshacer.',
    publish: 'Publicar',
    create: 'Crear',
    creating: 'Creando...',
    scenarioNamePlaceholder: 'ej. Plan de la próxima semana',
    // End of Spanish translations
  }
}

export function SettingsProvider({ children }: { children: ReactNode }): React.JSX.Element {
  const [settings, setSettings] = useState<Settings>({
    language: 'en',
    theme: 'dark',
    companyName: 'My Company',
    companyLogo: '',
    openingTime: '08:00',
    closingTime: '20:00',
    autoUpdate: 'true',
    showCalendar: true,
    visibleStats: {
      monthlyTarget: true,
      weeklyTarget: true,
      monthlyDiff: true,
      weeklyDiff: true,
      totalWorked: true,
      lifetimeBalance: true
    }
  })
  const [isLoading, setIsLoading] = useState(true)

  useEffect(() => {
    loadSettings()
  }, [])

  useEffect(() => {
    const root = window.document.documentElement
    root.classList.remove('light', 'dark')
    root.classList.add(settings.theme)
  }, [settings.theme])

  const loadSettings = async (): Promise<void> => {
    try {
      const stored = await window.api.settings.getAll()
      // Parse visibleStats if it exists
      let parsedStats = {}
      if (stored.visibleStats) {
        try {
          parsedStats = JSON.parse(stored.visibleStats)
        } catch (e) {
          console.error('Failed to parse visibleStats', e)
        }
      }
      
      // Merge with defaults to ensure all keys exist
      setSettings((prev) => ({ 
        ...prev, 
        ...stored,
        showCalendar: stored.showCalendar !== undefined ? (String(stored.showCalendar) === 'true') : prev.showCalendar,
        visibleStats: {
          ...prev.visibleStats,
          ...parsedStats
        }
      }))
    } catch (error) {
      console.error('Failed to load settings:', error)
    } finally {
      setIsLoading(false)
    }
  }

  const updateSetting = async (key: keyof Settings, value: any): Promise<void> => {
    try {
      // Optimistic update
      setSettings((prev) => ({ ...prev, [key]: value }))
      
      const valueToStore = typeof value === 'object' ? JSON.stringify(value) : String(value)
      await window.api.settings.update(key, valueToStore)
    } catch (error) {
      console.error(`Failed to update setting ${key}:`, error)
      // Revert on error (could be improved)
      loadSettings()
    }
  }

  const t = (key: string): string => {
    const lang = settings.language as keyof typeof translations
    return translations[lang]?.[key] || key
  }

  return (
    <SettingsContext.Provider value={{ settings, updateSetting, t, isLoading }}>
      {children}
    </SettingsContext.Provider>
  )
}
